parameters:
  - name: host
    displayName: Linux Hostname (example.com)
    type: string
    default: jamacer
    values:
      - asuspn51
      - jamacer
resources:
  repositories:
    - repository: templates
      type: github
      name: JamesJonesConsulting/gitlab-runner-agent-on-podman
      endpoint: JamesJonesConsulting
      # type: git
      # name: https://github.com/JamesJonesConsulting/gitlab-runner-agent-on-podman.git
      # ref: refs/heads/main     
  containers: 
    - container: podman-dind
      image: registry.gitlab.com/jamesjonesconsulting/podman-dind-like:latest
      endpoint: JamesJonesConsultingDockerGitlab
jobs: 
  - template: setup.yml
    parameters:
      host: ${{ parameters.host }}
# extends:
#   template: setup.yml@templates    
#   parameters:
#     host: ${{ parameters.host }}

