parameters:
  - name: host
    type: string
  - name: hosts
    type: object
    default:      
      all:
      hosts:
          asuspn51:
            ansible_host: 127.0.0.1
          jamacer:
            ansible_host: 127.0.0.1
      children:
          gitlab_runners:
          hosts:
              asuspn51:
              jamacer:
resources:
  repositories:
    - repository: inventory
      type: github
      name: JamesJonesConsulting/AnsibleInventory
      endpoint: JamesJonesConsulting      
  containers: 
    - container: podman-dind
      image: registry.gitlab.com/jamesjonesconsulting/podman-dind-like:latest
      endpoint: JamesJonesConsultingDockerGitlab
      options: --userns=keep-id --privileged --user root
      mapDockerSocket: false
jobs:
  - deployment: gitlab_runner_deployment
    displayName: Gitlab Runner Deployment
    pool: FedoraHosted
    environment: GitLab
    container: podman-dind
    variables:
      - group: Connections
    strategy:
      runOnce:
        deploy:
          steps: 
            - checkout: self 
              path: s/pipeline
            - checkout: inventory
              path: s/inventory
            - bash: |
                eval $(ssh-agent); ssh-add <(echo "${SSH_KEY}" | base64 -d);
                ansible-galaxy collection install -r ansible/requirements.yml -f 
                ansible-playbook -i $(Build.SourcesDirectory)/template/home/hosts --user $(default_user) ansible/playbook.yml --extra-vars 'host_or_group=${{ parameters.host }}'-b -vvvv
              workingDirectory: $(Build.SourcesDirectory)/pipeline
              displayName: Connect to host and setup GitLab Runner with Podman
              env:
                SSH_KEY: $(default_ssh_key)
