- hosts: "{{ host_or_group }}"
  vars_files:
    - ./vars/main.yml
  tasks: 
    - name: Read in the vault
      ansible.builtin.include_vars:
        file: "{{ gitlab_vaulted_variables }}"
        name: gitlab
    - ansible.builtin.include_role:
        name: jamesjonesconsulting.gitlab_runner_on_podman.gitlab_runner_setup
      vars:
        gitlab_runner_username: gitlab-runner
        gitlab_runner_podman_group: docker
        gitlab_runner_url: "{{ gitlab_runner_home_url }}"
        gitlab_runner_registration_token: "{{ gitlab.gitlab_registration_token }}"
        gitlab_runner_tags: "{{ gitlab_runner_host_tags }}"
        gitlab_runner_count: "{{ gitlab_runner_host_count | default(1) }}"
        gitlab_runner_run_untagged: "{{ gitlab_runner_host_run_untagged | default(true) }}"
