- hosts: "{{ host_or_group }}"
  vars_files:
    - ./vars/main.yml
  tasks: 
    - include_role:
        name: jamesjonesconsulting.gitlab_runner_on_podman.gitlab_runner_setup
      vars:
        gitlab_runner_username: gitlab-runner
        gitlab_runner_podman_group: docker
        gitlab_runner_url: "{{ gitlab_runner_home_url }}"
        gitlab_runner_registration_token: abcdefghijklmnopqrstuvwxyz
        gitlab_runner_tags: "{{ gitlab_runner_host_tags }}"

